### ISSUE TITLE
Add a person to a meeting

### ISSUE THREAD

**Issue by MichaelJHTaggart** [Reed-Broadhead/VC-Connect#3]
When ever someone would like to join a meeting they need the meeting id. 
[https://docs.dyte.io/api/?v=v2#/operations/add_participant](https://docs.dyte.io/api/?v=v2#/operations/add_participant)

This can be provided by creating the meeting:
[https://docs.dyte.io/api/?v=v2#/operations/create_meeting](https://docs.dyte.io/api/?v=v2#/operations/create_meeting)

Or by fetching the existing meeting information:
[https://docs.dyte.io/api/?v=v2#/operations/get_meeting](https://docs.dyte.io/api/?v=v2#/operations/get_meeting)

Then add the participant:
[https://docs.dyte.io/api/?v=v2#/operations/add_participant](https://docs.dyte.io/api/?v=v2#/operations/add_participant)

**Describe the solution you'd like**

- [x] Anyone can join a meeting

**Describe alternatives you've considered**

**Additional context**

**Comment by Reed-Broadhead** [comment]
I think we could do something similar to what Google Meets does where whenever a participant attempts to join a room they are taken to a waiting page until the room host permits them to enter. It could work by having the users routed to a waiting page every time they try to use the ID to join a room, then once the host permits them to join we could give the user the auth token.

**Comment by Reed-Broadhead** [comment]
Hey guys, I made some changes on branch "iss2" that solve this issue. I made a comment about the changes on issue #2 if you want more information.

Feel free to take a look at my changes and let me know if anything looks wrong.

**Comment by Reed-Broadhead** [comment]
Hey guys, my last comment is wrong. the changes I made do not solve this issue they solve part of the issue. The code I made adds a route that checks the URL for an authToken, then trys to connect you to a meeting using that authToken; however, there are still more steps needed to complete this issue. We still need a way for the user to get an auth token for the meeting so they can connect to it.

**Comment by MichaelJHTaggart** [comment]
Inside the meeting:

Copy - button
*Email - is sent out for participants to join (done in server OR opens email up for them)*

Frontend:

- [ ] Need a copy URL button to share with friends
- [ ] Join a meeting button

Backend: 

- [ ] Route that adds a participant.

**Comment by Reed-Broadhead** [comment]
I just pushed up some local changes to branch issue3 that makes a new route and added a join meeting form.  I've tested them a couple of time and both of them seem to work and should solve 2 of the three problems were dealing with right now. 

Feel free to pull down the branch and take a look at it.
